### DISCUSSION TITLE
How does Qbitrr decide what is allowed to seed?

### DISCUSSION THREAD

**Discussion by Tanguille** [Feramance/qBitrr#36] [Q&A] [answered]
Does anyone know how qbitrr decides what is allowed to seed? It keeps pausing torrents I want to seed. Manually setting the `qBitrr-allowed_seeding`  tag doesn't work because qbitrr will remove it again. I don't know what is different about those 36 torrents from my total 153. 
![image](https://github.com/Feramance/qBitrr/assets/91473554/e205b220-1717-4093-809f-11eb1162a6aa)

**Comment by Feramance** [comment]
That's based on the seeding maximums defined in the config, default configs have no seeding limit therefore all torrents will be allowed seeding. If a torrent reaches max seeding/ratio, then it's no longer tagged as allowed seeding and seeding is halted

**Reply by Tanguille** [reply]
All my limits seem to be on `-1` so there must be something else overriding this. Is there a way I can just override this and seed everything or something? I checked on Qbitorrent andProwlarr and also have no limits there.

**Reply by Feramance** [reply]
If they're all -1, check qittorrent, otherwise they should be allowed to seed indefinitely provided there are peers requesting the torrent

**Reply by Feramance** [reply]
If not please describe further the behaviour you're experiencing and what you're trying to accomplish

**Reply by Feramance** [reply]
Also note that only torrents in the categories specified in the config will maintain that tag when appropriate

**Reply by Tanguille** [reply]
So if there are no peers requesting it will stop to seed even if you have no limits? I want everything to seed.

**Reply by Feramance** [reply]
Please send over your config

**Reply by Tanguille** [reply]
Thanks for doing this effort. Here is my config with a few sensible values hidden: 
```toml
[Settings]
# Level of logging; One of CRITICAL, ERROR, WARNING, NOTICE, INFO, DEBUG, TRACE
ConsoleLevel = "INFO"

# Enable logging to files
Logging = true

# Folder where your completed downloads are put into. Can be found in qBitTorrent -> Options -> Downloads -> Default Save Path
CompletedDownloadFolder = "/completed_downloads"

# Time to sleep for if there is no internet (in seconds: 600 = 10 Minutes)
NoInternetSleepTimer = 15

# Time to sleep between reprocessing torrents (in seconds: 600 = 10 Minutes)
LoopSleepTimer = 5

# Add torrents to this category to mark them as failed
FailedCategory = "failed"

# Add torrents to this category to trigger them to be rechecked properly
RecheckCategory = "recheck"

# Ignore Torrents which are younger than this value (in seconds: 600 = 10 Minutes)
# Only applicable to Re-check and failed categories
IgnoreTorrentsYoungerThan = 180

# URL to be pinged to check if you have a valid internet connection
# These will be pinged a **LOT** make sure the service is okay with you sending all the continuous pings.
PingURLS = ["one.one.one.one", "dns.google.com"]

# FFprobe auto updates, binaries are downloaded from https://ffbinaries.com/downloads
# If this is disabled and you want ffprobe to work
# Ensure that you add the binary for your platform into ~/qBitrr/qBitManager i.e "C:\Users\<user>\qBitrr\qBitManager\ffprobe.exe"
# If no `ffprobe` binary is found in the folder above all ffprobe functionality will be disabled.
# By default this will always be on even if config does not have these key - to disable you need to explicitly set it to `False`
FFprobeAutoUpdate = true

[qBit]
# If this is enable qBitrr can run in a headless mode where it will only process searches.
# If media search is enabled in their individual categories
# This is useful if you use for example Sabnzbd/NZBGet for downloading content but still want the faster media searches provided by qbit
Disabled = false

# qBit WebUI Port - Can be found in Options > Web UI (called "IP Address")
Host = "192.168.0.27"

# qBit WebUI Port - Can be found in Options > Web UI (called "Port" on top right corner of the window)
Port = 10095

# qBit WebUI Authentication - Can be found in Options > Web UI > Authentication
UserName = "<hidden>"

# If you set "Bypass authentication on localhost or whitelisted IPs" remove this field.
Password = "<hidden>"


[Sonarr-TV]
# Toggle whether to manage the Servarr instance torrents.
Managed = true

# The URL used to access Servarr interface (if you use a domain enter the domain without a port)
URI = "http://sonarr.ix-sonarr.svc.cluster.local:8989/"

# The Servarr API Key, Can be found it Settings > General > Security
APIKey = "<hidden>"

# Category applied by Servarr to torrents in qBitTorrent, can be found in Settings > Download Clients > qBit > Category
Category = "tv-sonarr"

# Toggle whether to send a query to Servarr to search any failed torrents
ReSearch = true

# The Servarr's Import Mode(one of Move, Copy or Hardlink)
importMode = "Hardlink"

# Timer to call RSSSync (In minutes) - Set to 0 to disable (Values below 5 can cause errors for maximum retires)
RssSyncTimer = 1

# Timer to call RefreshDownloads to update the queue. (In minutes) - Set to 0 to disable (Values below 5 can cause errors for maximum retires)
RefreshDownloadsTimer = 1

# Error messages shown my the Arr instance which should be considered failures.
# This entry should be a list, leave it empty if you want to disable this error handling.
# If enabled qBitrr will remove the failed files and tell the Arr instance the download failed
ArrErrorCodesToBlocklist = []


[Sonarr-TV.EntrySearch]
# All these settings depends on SearchMissing being True and access to the Servarr database file.

# Should search for Missing files?
SearchMissing = false

# Should search for specials episodes? (Season 00)
AlsoSearchSpecials = false

# Maximum allowed Searches at any one points (I wouldn't recommend settings this too high)
# Sonarr has a hardcoded cap of 3 simultaneous tasks
SearchLimit = 3

# Servarr Datapath file path
# This is required for any of the search functionality to work
# The only exception for this is the "ReSearch" setting as that is done via an API call.
DatabaseFile = "/config/sonarr.db"

# It will order searches by the year the EPISODE was first aired
SearchByYear = true

# Reverse search order (Start searching oldest to newest)
SearchInReverse = false

# Delay between request searches in seconds
SearchRequestsEvery = 300

# Search movies which already have a file in the database in hopes of finding a better quality version.
DoUpgradeSearch = false

# Do a quality unmet search for existing entries.
QualityUnmetSearch = true

# Once you have search all files on your specified year range restart the loop and search again.
SearchAgainOnSearchCompletion = true

# Search by series instead of by episode
SearchBySeries = true

# Prioritize Today's releases (Similar effect as RSS Sync, where it searches today's release episodes first, only works on Sonarr).
PrioritizeTodaysReleases = true


[Sonarr-TV.EntrySearch.Overseerr]
# Search Overseerr for pending requests (Will only work if 'SearchMissing' is enabled.)
# If this and Ombi are both enable, Ombi will be ignored
SearchOverseerrRequests = true

# Overseerr's URI
OverseerrURI = "http://jellyseerr.ix-jellyseerr.svc.cluster.local:10241/"

# Overseerr's API Key
OverseerrAPIKey = "<hidden>"

# Only process approved requests
ApprovedOnly = true

#Only for 4K Instances
Is4K = false


[Sonarr-TV.Torrent]
# Set it to regex matches to respect/ignore case.
CaseSensitiveMatches = false

# These regex values will match any folder where the full name matches the specified values here, comma separated strings.
# These regex need to be escaped, that's why you see so many backslashes.
FolderExclusionRegex = [
    "\\bfeaturettes?\\b",
    "\\bsamples?\\b",
    "\\bscreens?\\b",
    "\\bspecials?\\b",
    "\\bova\\b",
    "\\bnc(ed|op)?(\\\\d+)?\\b",
]

# These regex values will match any folder where the full name matches the specified values here, comma separated strings.
# These regex need to be escaped, that's why you see so many backslashes.
FileNameExclusionRegex = [
    "\\bncop\\\\d+?\\b",
    "\\bnced\\\\d+?\\b",
    "\\bsample\\b",
    "brarbg.com\\b",
    "\\btrailer\\b",
    "music video",
    "comandotorrents.com",
]

# Only files with these extensions will be allowed to be downloaded, comma separated strings, leave it empty to allow all extensions
FileExtensionAllowlist = [
    ".mp4",
    ".mkv",
    ".sub",
    ".ass",
    ".srt",
    ".!qB",
    ".parts",
    ".avi",
]

# Auto delete files that can't be playable (i.e .exe, .png)
AutoDelete = true

# Ignore Torrents which are younger than this value (in seconds: 600 = 10 Minutes)
IgnoreTorrentsYoungerThan = 600

# Maximum allowed remaining ETA for torrent completion (in seconds: 3600 = 1 Hour)
# Note that if you set the MaximumETA on a tracker basis that value is favoured over this value
MaximumETA = 604800

# Do not delete torrents with higher completion percentage than this setting (0.5 = 50%, 1.0 = 100%)
MaximumDeletablePercentage = 0.99

# Ignore slow torrents.
DoNotRemoveSlow = true

[Sonarr-TV.Torrent.SeedingMode]
# Set the maximum allowed download rate for torrents
# Set this value to -1 to disabled it
# Note that if you set the DownloadRateLimit on a tracker basis that value is favoured over this value
DownloadRateLimitPerTorrent = -1

# Set the maximum allowed upload rate for torrents
# Set this value to -1 to disabled it
# Note that if you set the UploadRateLimit on a tracker basis that value is favoured over this value
UploadRateLimitPerTorrent = -1

# Set the maximum allowed upload ratio for torrents
# Set this value to -1 to disabled it
# Note that if you set the MaxUploadRatio on a tracker basis that value is favoured over this value
MaxUploadRatio = -1

# Set the maximum seeding time for torrents
# Set this value to -1 to disabled it
# Note that if you set the MaxSeedingTime on a tracker basis that value is favoured over this value
MaxSeedingTime = -1

# Enable if you want to remove dead trackers
RemoveDeadTrackers = false
# If "RemoveDeadTrackers" is set to true then remove trackers with the following messages
RemoveTrackerWithMessage = [
    "skipping tracker announce (unreachable)",
    "No such host is known",
    "unsupported URL protocol",
    "info hash is not authorized with this tracker",
]

# You can have multiple trackers set here or none just add more subsections.


[Radarr]
# Toggle whether to manage the Servarr instance torrents.
Managed = true

# The URL used to access Servarr interface (if you use a domain enter the domain without a port)
URI = "http://radarr.ix-radarr.svc.cluster.local:7878/"

# The Servarr API Key, Can be found it Settings > General > Security
APIKey = "<hidden>"

# Category applied by Servarr to torrents in qBitTorrent, can be found in Settings > Download Clients > qBit > Category
Category = "radarr"

# Toggle whether to send a query to Servarr to search any failed torrents
ReSearch = true

# The Servarr's Import Mode(one of Move, Copy or Hardlink)
importMode = "Hardlink"

# Timer to call RSSSync (In minutes) - Set to 0 to disable (Values below 5 can cause errors for maximum retires)
RssSyncTimer = 1

# Timer to call RefreshDownloads to update the queue. (In minutes) - Set to 0 to disable (Values below 5 can cause errors for maximum retires)
RefreshDownloadsTimer = 1

# Error messages shown my the Arr instance which should be considered failures.
# This entry should be a list, leave it empty if you want to disable this error handling.
# If enabled qBitrr will remove the failed files and tell the Arr instance the download failed
ArrErrorCodesToBlocklist = []


[Radarr.EntrySearch]
# All these settings depends on SearchMissing being True and access to the Servarr database file.

# Should search for Missing files?
SearchMissing = false

# Should search for specials episodes? (Season 00)
AlsoSearchSpecials = false

# Maximum allowed Searches at any one points (I wouldn't recommend settings this too high)
# Radarr has a default of 3 simultaneous tasks, which can be increased up to 10 tasks
# If you set the environment variable of "THREAD_LIMIT" to a number between and including 2-10
# Radarr devs have stated that this is an unsupported feature so you will not get any support for doing so from them.
# That being said I've been daily driving 10 simultaneous tasks for quite a while now with no issues.
SearchLimit = 10

# Servarr Datapath file path
# This is required for any of the search functionality to work
# The only exception for this is the "ReSearch" setting as that is done via an API call.
DatabaseFile = "/config/radarr.db"

# It will order searches by the year the EPISODE was first aired
SearchByYear = true

# Reverse search order (Start searching oldest to newest)
SearchInReverse = false

# Delay between request searches in seconds
SearchRequestsEvery = 300

# Search movies which already have a file in the database in hopes of finding a better quality version.
DoUpgradeSearch = false

# Do a quality unmet search for existing entries.
QualityUnmetSearch = false

# Once you have search all files on your specified year range restart the loop and search again.
SearchAgainOnSearchCompletion = true


[Radarr.EntrySearch.Overseerr]
# Search Overseerr for pending requests (Will only work if 'SearchMissing' is enabled.)
# If this and Ombi are both enable, Ombi will be ignored
SearchOverseerrRequests = true

# Overseerr's URI
OverseerrURI = "http://jellyseerr.ix-jellyseerr.svc.cluster.local:10241/"

# Overseerr's API Key
OverseerrAPIKey = "<hidden>"

# Only process approved requests
ApprovedOnly = true

#Only for 4K Instances
Is4K = false


[Radarr.Torrent]
# Set it to regex matches to respect/ignore case.
CaseSensitiveMatches = false

# These regex values will match any folder where the full name matches the specified values here, comma separated strings.
# These regex need to be escaped, that's why you see so many backslashes.
FolderExclusionRegex = [
    "\\bfeaturettes?\\b",
    "\\bsamples?\\b",
    "\\bscreens?\\b",
    "\\bspecials?\\b",
    "\\bova\\b",
    "\\bnc(ed|op)?(\\\\d+)?\\b",
]

# These regex values will match any folder where the full name matches the specified values here, comma separated strings.
# These regex need to be escaped, that's why you see so many backslashes.
FileNameExclusionRegex = [
    "\\bncop\\\\d+?\\b",
    "\\bnced\\\\d+?\\b",
    "\\bsample\\b",
    "brarbg.com\\b",
    "\\btrailer\\b",
    "music video",
    "comandotorrents.com",
]

# Only files with these extensions will be allowed to be downloaded, comma separated strings, leave it empty to allow all extensions
FileExtensionAllowlist = [
    ".mp4",
    ".mkv",
    ".sub",
    ".ass",
    ".srt",
    ".!qB",
    ".parts",
    ".avi",
]

# Auto delete files that can't be playable (i.e .exe, .png)
AutoDelete = true

# Ignore Torrents which are younger than this value (in seconds: 600 = 10 Minutes)
IgnoreTorrentsYoungerThan = 180

# Maximum allowed remaining ETA for torrent completion (in seconds: 3600 = 1 Hour)
# Note that if you set the MaximumETA on a tracker basis that value is favoured over this value
MaximumETA = 604800

# Do not delete torrents with higher completion percentage than this setting (0.5 = 50%, 1.0 = 100%)
MaximumDeletablePercentage = 0.99

# Ignore slow torrents.
DoNotRemoveSlow = true

[Radarr.Torrent.SeedingMode]
# Set the maximum allowed download rate for torrents
# Set this value to -1 to disabled it
# Note that if you set the DownloadRateLimit on a tracker basis that value is avoured over this value
DownloadRateLimitPerTorrent = -1

# Set the maximum allowed upload rate for torrents
# Set this value to -1 to disabled it
# Note that if you set the UploadRateLimit on a tracker basis that value is favoured over this value
UploadRateLimitPerTorrent = -1

# Set the maximum allowed upload ratio for torrents
# Set this value to -1 to disabled it
# Note that if you set the MaxUploadRatio on a tracker basis that value is favoured over this value
MaxUploadRatio = -1

# Set the maximum seeding time for torrents
# Set this value to -1 to disabled it
# Note that if you set the MaxSeedingTime on a tracker basis that value is favoured over this value
MaxSeedingTime = -1

# Enable if you want to remove dead trackers
RemoveDeadTrackers = false

# If "RemoveDeadTrackers" is set to true then remove trackers with the following messages
RemoveTrackerWithMessage = [
    "skipping tracker announce (unreachable)",
    "No such host is known",
    "unsupported URL protocol",
    "info hash is not authorized with this tracker",
    ]
```
