### ISSUE TITLE
Temp profile switching

### ISSUE THREAD

**Issue by drmetro09** [Feramance/qBitrr#141]
Error , image for the reference 
![IMG_1586](https://github.com/user-attachments/assets/32227493-17a5-465d-8ca6-abcfa20772a8)

**Comment by Feramance** [comment]
My bad, I'll fix this shortly

**Comment by drmetro09** [comment]
Ok

**Comment by Feramance** [comment]
Resolved in v4.10.2

**Comment by drmetro09** [comment]
![IMG_1587](https://github.com/user-attachments/assets/893fe395-211a-41bf-94bd-e54389637dbb)

another error @Feramance

**Comment by Feramance** [comment]
If v4.10.3 doesn't work either, please attach full logs

**Comment by drmetro09** [comment]
Ok

**Comment by drmetro09** [comment]
The shifting of profiles that we discussed it’s not at all working it just shifts from main profile to temp 1 thats it and it also gives that above error, so qbitrr is stopped now

**Comment by Feramance** [comment]
So please send logs with regards to the error, and it should switch from one to the next every loop, so 15 or longer, depending on the number  of search commands

**Comment by drmetro09** [comment]
> So please send logs with regards to the error, and it should switch from one to the next every loop, so 15 or longer, depending on the number of search commands

It doesn’t, i see it from radarr it just shifts from main to temp 1 profile and update v4.10.2 has that error is showed above

**Comment by drmetro09** [comment]
> ![IMG_1587](https://private-user-images.githubusercontent.com/143595315/392487043-893fe395-211a-41bf-94bd-e54389637dbb.jpeg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzMzNDQzMjgsIm5iZiI6MTczMzM0NDAyOCwicGF0aCI6Ii8xNDM1OTUzMTUvMzkyNDg3MDQzLTg5M2ZlMzk1LTIxMWEtNDFiZi05NGJkLWU1NDM4OTYzN2RiYi5qcGVnP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MTIwNCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDEyMDRUMjAyNzA4WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9ZTJkZTc3OWY4NmFiNDExMTlmZGViMjkwNDQxZjhlZGNmNDJiZDEzNjNjYmNjZTBlMzBlZDY4NjljNTEwZjVkNiZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QifQ.1vFVGpiKT51FrXkt4J1Qa42gs1VbftNWlDgGIKf2V8o)
> 
> another error @Feramance

This is in 4.10.1 , 2 …

**Comment by drmetro09** [comment]
Update: the error was due to jumbling in the sequence of quality profiles, the previous sequence gave the error the horizontal sequence of quality profiles in main and temp should be exact matching or else it gives the error , basically whatever names is in the main profile same should  be in temp profile

**Comment by drmetro09** [comment]
However the shifting of quality profiles doesn’t happen

**Comment by Feramance** [comment]
Please send me your current quality profile config so I can check

**Comment by drmetro09** [comment]
Python error in v4.10.3 image attached 
![IMG_1593](https://github.com/user-attachments/assets/395e3789-41d4-4a35-88d5-26f19e122a41)

**Comment by Feramance** [comment]
Please send me your config as you have something wrong in your temp profile definitions

**Comment by drmetro09** [comment]
Here  is how I set it up
![IMG_1597](https://github.com/user-attachments/assets/8acd91d4-0dac-4943-a144-d58902e4c41b)

**Comment by Feramance** [comment]
That will never work, is it meant to cycle from 1>3>4>5?

**Comment by Feramance** [comment]
I know, but what's the order you're trying to achieve?

**Comment by drmetro09** [comment]
Up down , up down, up down same as we discussed yesterday… since yesterday qbitrr is running but quality profiles didnt shift

**Comment by drmetro09** [comment]
I also tried other orders but they also dont shift

**Comment by Feramance** [comment]
Please give me the order with the exact profile names.

From the screenshot I imagine the config needs to be set as follows:
```toml
# Main quality profile (To pair quality profiles, ensure they are in the same order as in the temp profiles)
MainQualityProfile = ["1.)Default_local+Eng_1080p +720p", "3.) local 1080p+720p ", "5.) local only_1080p "]

# Temp quality profile (To pair quality profiles, ensure they are in the same order as in the main profiles)
TempQualityProfile = ["3.) local 1080p+720p ", "5.) local only_1080p ", "4.) English only_1080p "]
```
