### ISSUE TITLE
Failed to connected to the internet

### ISSUE THREAD

**Issue by bruvv** [Feramance/qBitrr#146]
For some reason I am seeing a lot of failed to connected to the internet errors, why is that? Even with trace on it makes no sense, I have a 1000 fiber connection and yes I know 100% that it is online my server. I also changed the `PingURLS` to some local sites but that makes no difference.

```
qbitrr  | [2024-12-11 00:44:52] [pid:       7][tid:140353803631488] TRACE   : qBitrr.Manager    : Successfully connected to http://qbittorrent:8080
qbitrr  | [2024-12-11 00:44:52] [pid:       7][tid:140353803631488] TRACE   : qBitrr.Sonarr-TV  : Successfully connected to http://sonarr:8989
qbitrr  | [2024-12-11 00:44:52] [pid:       7][tid:140353803631488] CRITICAL: qBitrr.Sonarr-TV  : Failed to connected to the internet, sleeping for 0:00:15
qbitrr  | [2024-12-11 00:44:52] [pid:       9][tid:140353803631488] TRACE   : qBitrr.Manager    : Successfully connected to http://qbittorrent:8080
qbitrr  | [2024-12-11 00:44:52] [pid:       9][tid:140353803631488] TRACE   : qBitrr.Radarr-1080: Successfully connected to http://radarr:7878
qbitrr  | [2024-12-11 00:44:52] [pid:       9][tid:140353803631488] CRITICAL: qBitrr.Radarr-1080: Failed to connected to the internet, sleeping for 0:00:15
qbitrr  | [2024-12-11 00:44:56] [pid:      10][tid:140353803631488] TRACE   : qBitrr.Manager    : Successfully connected to http://qbittorrent:8080
qbitrr  | [2024-12-11 00:44:56] [pid:      10][tid:140353803631488] DEBUG   : qBitrr.Recheck    : No downloads in category, sleeping for 0:00:05
qbitrr  | [2024-12-11 00:44:56] [pid:      11][tid:140353803631488] TRACE   : qBitrr.Manager    : Successfully connected to http://qbittorrent:8080
qbitrr  | [2024-12-11 00:44:56] [pid:      11][tid:140353803631488] DEBUG   : qBitrr.Failed     : No downloads in category, sleeping for 0:00:05
qbitrr  | [2024-12-11 00:44:59] [pid:       8][tid:140353803631488] DEBUG   : qBitrr.Radarr-1080: Current year 1972
```

Running this in docker:
```
  qbitrr:
    image: feramance/qbitrr:latest
    container_name: qbitrr
    user: 1030:65539 # Required to ensure the container is run as the user who has perms to see the 2 mount points and the ability to write to the CompletedDownloadFolder mount
    tty: true # Ensure the output of docker-compose logs qBitrr are properly colored.
    restart: unless-stopped
    # networks: This container MUST share a network with your Sonarr/Radarr instances
    environment:
      - PUID=1030
      - PGID=65539
      - TZ=Europe/Amsterdam
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ./qbitrr:/config  # Config folder for qBitrr
      - /volume1/downloads/complete:/completed_downloads:rw # The script will ALWAYS require write permission in this folder if mounted, this folder is used to monitor completed downloads and if not present will cause the script to ignore downloaded file monitoring.
      # Now just to make sure it is clean, when using this script in a docker you will need to ensure you config.toml values reflect the mounted folders.
      # The same would apply to Settings.CompletedDownloadFolder
      # e.g CompletedDownloadFolder = /completed_downloads/folder/in/container
    depends_on: # Not needed but this ensures qBitrr only starts if the dependencies are up and running
      - qbittorrent
      - radarr
      - sonarr
```

Can this be related to https://github.com/Feramance/qBitrr/issues/144 alhtough my qbitorrent client is not firewalled nor disconnected
